source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins
# gem "sprockets", "4.0.0.beta6"
# gem "autoprefixer-rails"
# gem "jekyll-paginate"
# gem "jekyll-sitemap"
# gem "jekyll-assets"
# gem "html-proofer"
# gem "image_optim"
# gem "mini_magick"
# gem "uglifier"
# gem "jekyll"
# gem "jemoji"
# gem "sass"
